version: '3.9'

services:
  personApp:
    image: person:0.0.1
    container_name: person-app
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_URL=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:5432/postgres
      - DB_USERNAME=postgres.rnuvrzhrnhhstqzgxuwd
      - DB_PASSWORD=d4d5D6amoamimama#
#  personDB:
#    image: postgres:15.3
#    container_name: person-db
#    restart: always
#    ports:
#      - 5432:5432
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=password
#    volumes:
#      - ./postgres:/var/lib/postgresql/data